### ISSUE TITLE
Error after update: Cannot find module 'duplexify'

### ISSUE THREAD

**Issue by cupideias** [ndxbxrme/generator-angular-meteor#28]
I updated my generator-angular-meteor and know I have this error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'duplexify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/index.js:10:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Does someone know how to fix it?

**Comment by ndxbxrme** [comment]
hey diego
i haven't seen that error before, my guess would be that you need to update your version of meteor too.
i'll do some investigating, what is your os and what setup are you choosing?

**Comment by cupideias** [comment]
I'm using Mac OS X El Captain.
It begin after I update Meteor and the generator-angular-meteor.
