### ISSUE TITLE
Error: EACCES, mkdir '/appName'

### ISSUE THREAD

**Issue by ColonelBundy** [ndxbxrme/generator-angular-meteor#36]
**Running** `yo angular-meteor appName` results in:

```
/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: EACCES, mkdir '/appName'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as mkdir] (/tools/fs/files.js:1334:20)
    at Object.files.mkdir_p (/tools/fs/files.js:405:11)
    at Object.files.cp_r (/tools/fs/files.js:444:9)
    at Command.buildCommands.minArgs [as func] (/tools/cli/commands.js:680:11)
    at /tools/cli/main.js:1378:23
    - - - - -
Something went wrong running meteor, please make sure you have it installed properly.  https://www.meteor.com/
```

**Versions:** npm 3.7.1, node 4.3.0, Meteor 1.2.1 in Centos 6.7

All installed and working properly.

**Running** `sudo yo angular-meteor appName` results in:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by ndxbxrme** [comment]
hey marcus,
i'm not sure what is going on there.  it looks like meteor is having troubles creating it's directory.
the only thing the generator does at that point is to run

```
meteor create appName
```

does that command work for you?

i'll try making a centos virtual machine this weekend to see if i can recreate the issue

**Comment by ColonelBundy** [comment]
Hi there! 

Yup, `meteor create appName` Works just fine :)
