### ISSUE TITLE
Bower is not usable

### ISSUE THREAD

**Issue by haipham23** [ndxbxrme/generator-angular-meteor#40]
I install package using bower, such as: `bower install --save angularjs-slider`
Then I run `meteor` and get the following message

```
While building the application:
error: Bower dependencies list must be a dictionary in bower_components\angularjs-slider\bower.json
packages/bower/plugin/handler.js:209:1: Cannot read property 'name' of undefined (compiling
bower_components/angularjs-slider/bower.json)
at getDependencies (packages/bower/plugin/handler.js:209:1)
at packages/bower/plugin/handler.js:220:1
at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
at getDependencies (packages/bower/plugin/handler.js:219:1)
at bowerHandler (packages/bower/plugin/handler.js:76:1)
at Package (packages/bower/plugin/handler.js:262:1)
```

**Comment by ndxbxrme** [comment]
hey @haipham23 
i'll try to recreate the issue tonight

**Comment by ndxbxrme** [comment]
hey @haipham23 
sorry i haven't been around.
your issue is being caused by the mquandalle-bower package getting upset when it can't find a dependencies list in bower.json of the package being installed.  it seems to be a known issue but it isn't one that is going to be fixed https://github.com/mquandalle/meteor-bower/issues/107

it also looks like mquandalle-bower won't be supporting meteor 1.3

removing mquandalle-bower and replacing it with bozhao:bower solves this issue but meteor still won't build because it freaks out trying to process the angularjs-slider demo files:(

you could repackage the bower components and publish them to atmosphere, but that's a bit of a pain

i'll attempt to find a better solution

**Comment by mikkelking** [comment]
With Meteor 1.3 Bower is deprecated in favour of NPM, although this doesn't really solve the problem.
