### ISSUE TITLE
Error: ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by austingreendev** [ndxbxrme/generator-angular-meteor#42]
While trying to create a basic meteor-angular application I am getting the error below.  It is creating the basic directory, but not including any customizations.  

I believe it is just running the `meteor create appName` command

```
To run your new app:                          
  cd appName                                  
  meteor                                      

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                

events.js:154                                 
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, unlink '/Users/austin/GitRepos/appName/appName.html'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:980:18)
    at null.<anonymous> (/usr/local/lib/node_modules/generator-angular-meteor/generators/app/index.js:209:12)
    at Array.forEach (native)
    at module.exports.yeoman.generators.Base.extend.cleanMeteorDirectory (/usr/local/lib/node_modules/generator-angular-meteor/generators/app/index.js:208:32)
    at /usr/local/lib/node_modules/generator-angular-meteor/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Do you have any known work-arounds for this. 

NPM version: 3.6.0
Node version: v5.7.1

**Comment by StokedIndustries** [comment]
I just got this same error, was wondering what happened

**Comment by digvijaybhakuni** [comment]
getting the same error
`
To run your new app:  
  cd acmApp  
  meteor                                      

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                

events.js:141  
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, unlink '/home/ubuntu/workspace/acm/acmApp/acmApp.html'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at null.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/generator-angular-meteor/generators/app/index.js:209:12)
    at Array.forEach (native)
    at module.exports.yeoman.generators.Base.extend.cleanMeteorDirectory (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/generator-angular-meteor/generators/app/index.js:208:32)
    at /home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/generator-angular-meteor/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback](timers.js:383:17)
`

**Comment by austingreendev** [comment]
@digvijaybhakuni I mentioned a quick-fix to this in #41 .  This may help you or it may not, but it would be worth a shot.

**Comment by ndxbxrme** [comment]
hey guys
this is an issue with the generator not currently being compatible with meteor1.3 https://github.com/ndxbxrme/generator-angular-meteor/issues/41
i've implemented the temporary fix suggested by @austin94 
and there is an effort underway to make it compatible with 1.3 https://github.com/ndxbxrme/generator-angular-meteor/issues/43

check out the new version (v0.20.7)
